#!/usr/bin/env bash
#
# A git hook script to prevent committing files that contain:
#
# (1) Windows line-endings
# (2) trailing whitespace
# (3) non-ASCII characters
#
# Bypass it with the --no-verify option to git-commit.
#
# See also:
#
# http://stackoverflow.com/questions/591923/make-git-automatically-remove-trailing-whitespace-before-committing
#

if git rev-parse --verify HEAD >/dev/null 2>&1 ; then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

count=0 ; # number of files containing Windows line-endings, trailing whitespace and/or non-ASCII characters

# git secrets --pre_commit_hook -- "$@" ; count=$? ; # start with 1 if git secrets found a problem

for file in $(git diff-index --name-only --cached ${against} --) ; do
  [ -f "${file}" ] || continue ; # in case of "git rm"
  case $(basename "${file}") in
    *.gpg | *.db | *.pdf | *.keychain |*.ico | *.png | *.gif | *.jpg )
      # NOOP TODO find better way to determine "binary" files
    ;;
    * )
      pcregrep -q '\x0d$' "${file}" && {
        echo -e "Detected \033[7mWindows line-endings\033[0m in \033[7m${file}\033[0m" ;
        echo "Windows line-endings found on the following line(s)..." ;
        pcregrep -n '\x0d$' "${file}" | cat -e ;
        (( count++ )) ;
      }
      pcregrep -q '[[:blank:]]+$' "${file}" && {
        echo -e "Detected \033[7mtrailing whitespace\033[0m in \033[7m${file}\033[0m" ;
        echo "Trailing whitespace found on the following line(s)..." ;
        pcregrep -n '[[:blank:]]+$' "${file}" | cat -e ;
        (( count++ )) ;
      }
      pcregrep -q '[^\x00-\x7F]' "${file}" && {
        echo -e "Detected \033[7mnon-ASCII characters\033[0m in \033[7m${file}\033[0m" ;
        echo "Non-ASCII characters found on the following line(s)..." ;
        pcregrep -n --color --utf-8 '[^\x00-\x7F]' "${file}" ;
        (( count++ )) ;
      }
    ;;
  esac
  case $(basename "${file}") in
    *.rb )
      false && [ -x "$(command -v rubocop)" ] && ! rubocop "${file}" &> /dev/null && {
        rubocop "${file}" ;
        (( count++ )) ;
      }
    ;;
  esac
done

exit ${count} ;
